name: PR CI Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:
    types:
      - checks_requested

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - uses: actions/checkout@v5
      - name: Restore
        run: dotnet restore --nologo src
      - name: Build
        run: dotnet build --no-restore --nologo --configuration Release src

  code-style:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v5
      - name: Setup .Net 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore --nologo src
      - name: .Net Format
        run: dotnet format --no-restore --verify-no-changes -v diag src
